title: Tvhgooglemapi
description: "This was a simplemapi provider for Google Mail (both gmail and google for work.) It used IMAP for its implementation and would need a rewrite with the Gmail API, therefore it has been deprecated."
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
